GET https://luca.tech-challenges.toduba.it/api/notes
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ1c2VyMSIsImlhdCI6MTY1NDUwNzkwMH0.goEJqbmgQFWXFQT2gf3GIMNIpquyq4emW4VzUECLrxI

####

GET https://luca.tech-challenges.toduba.it/api/notes/5
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJ1c2VyMyIsImlhdCI6MTY1NDcxNzUwNSwiZXhwIjoxNjU0NzIxMTA1fQ.T6MVmrroUQR24sjuGZkZ_cqtAijnkjVYe4iqPVMpGWo


####

POST https://luca.tech-challenges.toduba.it/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJ1c2VyMyIsImlhdCI6MTY1NDcxNzUwNSwiZXhwIjoxNjU0NzIxMTA1fQ.T6MVmrroUQR24sjuGZkZ_cqtAijnkjVYe4iqPVMpGWo

{
    "title": "New note!",
    "content": "New interesting text",
    "date": "2022-06-06 12:03:03"

}

####

PUT https://luca.tech-challenges.toduba.it/api/notes/1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJ1c2VyMyIsImlhdCI6MTY1NDcxNzUwNSwiZXhwIjoxNjU0NzIxMTA1fQ.T6MVmrroUQR24sjuGZkZ_cqtAijnkjVYe4iqPVMpGWo

{
    "title": "New (UPDATED) note!",
    "content": "New (UPDATED) text!",
    "date": "2022-06-06 12:03:03"
}

###

DELETE https://luca.tech-challenges.toduba.it/api/notes/1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJ1c2VyMyIsImlhdCI6MTY1NDcxNzUwNSwiZXhwIjoxNjU0NzIxMTA1fQ.T6MVmrroUQR24sjuGZkZ_cqtAijnkjVYe4iqPVMpGWo

###

POST https://luca.tech-challenges.toduba.it/api/users/
Content-Type: application/json

{
    "username": "user1",
    "password": "ultrastrongpass"
}

####

POST https://luca.tech-challenges.toduba.it/api/login/
Content-Type: application/json

{
    "username": "user1",
    "password": "ultrastrongpass"
}